# Generated by Django 5.0.2 on 2024-04-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("product_name", models.CharField(max_length=20)),
                ("product_url", models.CharField(default="None", max_length=20)),
                ("product_image", models.ImageField(upload_to="")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.client"
                    ),
                ),
            ],
        ),
    ]
