# Generated by Django 5.0.2 on 2024-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_orders_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="instagram_profile_id",
            field=models.CharField(default="test", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "PAID"),
                    ("DELIVERED", "DELIVERED"),
                    ("FULFILED", "FULFILED"),
                    ("INFULFILED", "INFULFILED"),
                ],
                default="INFULFILED",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
