# Generated by Django 5.0.2 on 2024-04-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_client_instagram_profile_id_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product_image",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
