# Generated by Django 5.0.2 on 2024-05-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=144.0, max_digits=10),
            preserve_default=False,
        ),
    ]
