# Generated by Django 5.0.2 on 2024-05-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_product_name_remove_order_product_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product_urls",
        ),
    ]
