# Generated by Django 5.0.2 on 2024-05-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_order_product_urls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product_image",
        ),
    ]
